# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tic-tac-toe}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Skalnik"]
  s.date = %q{2010-11-04}
  s.default_executable = %q{tic-tac-toe}
  s.description = %q{A very simple tic-tac-toe game. Run `tic-tac-toe` to play.}
  s.email = %q{mike.skalnik@gmail.com}
  s.executables = ["tic-tac-toe"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/tic-tac-toe",
     "lib/tic-tac-toe.rb",
     "lib/tic-tac-toe/board.rb",
     "lib/tic-tac-toe/player.rb",
     "test/helper.rb",
     "test/test_tic-tac-toe.rb",
     "tic-tac-toe.gemspec"
  ]
  s.homepage = %q{http://github.com/skalnik/tic-tac-toe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple tic-tac-toe game!}
  s.test_files = [
    "test/helper.rb",
     "test/test_tic-tac-toe.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

